---
- git: repo=https://github.com/pleniec/pvpc-core.git dest=/home/vagrant/core
- shell: docker build -t core .
  args:
    chdir: /home/vagrant/core
- include: ../../postgres/tasks/start.yml
- include: ../../rabbitmq/tasks/start.yml
- include: ../../redis/tasks/start.yml
- shell: docker run -d --name core --link postgres:postgres --link redis:redis --link rabbitmq:rabbitmq core
- shell: docker exec core rake db:migrate
- shell: docker exec core rake db:seed
- shell: docker stop core
- include: ../../postgres/tasks/stop.yml
- include: ../../rabbitmq/tasks/stop.yml
- include: ../../redis/tasks/stop.yml
