---

- name: update and upgrade apt-get
  apt: update_cache=yes upgrade=full
  become: yes
  tags: configure

- name: install required packages
  apt: name={{ item }} state=present
  become: yes
  with_items: 
    - git
    - python-pip
  tags: configure

- name: install docker-py
  pip: name={{ item }} state=latest
  with_items: 
    - docker-py
  tags: configure

- name: install docker
  shell: curl -sSL https://get.docker.com/ | sh
  become: yes
  tags: configure


