---
- hosts: vm
  tasks:
    - git: repo=https://github.com/pleniec/pvpc-core.git dest=/home/vagrant/pvpc
    - shell: docker build -t pvpc .
      args:
       chdir: /home/vagrant/pvpc
    - shell: docker run -d -p 5432:5432 --name postgres postgres
    - pause: seconds=10
    - apt: name=postgresql-client-9.3
      sudo: yes
    - shell: createdb -h localhost -U postgres pvpc
    - shell: createuser -h localhost -U postgres pvpc
    - shell: docker create -p 6379:6379 --name redis redis
    - shell: docker run -d -p 3000:3000 --name pvpc --link postgres:postgres --link redis:redis pvpc
    - shell: docker exec pvpc rake db:migrate
    - shell: docker stop pvpc
    - shell: docker stop postgres
