---
- hosts: vm
  tasks:
    - git: repo=https://github.com/pleniec/pvpc-core.git dest=/home/vagrant/pvpc
    - shell: docker build -t pvpc .
      args:
       chdir: /home/vagrant/pvpc
    - shell: docker run -d -p 5432:5432 --name postgres postgres
    - pause: seconds=10
    - shell: docker exec postgres {{ item }} -h localhost -U postgres pvpc
      with_items:
        - createdb
        - createuser
    - shell: docker run -d -p 5672:5672 -p 15672:15672 --name rabbitmq frodenas/rabbitmq
    - pause: seconds=10
    - shell: docker exec rabbitmq rabbitmqctl change_password rabbitmq rabbitmq
    - shell: docker run -d -p 6379:6379 --name redis redis
    - shell: docker run -d -p 3000:3000 --name pvpc --link postgres:postgres --link redis:redis --link rabbitmq:rabbitmq pvpc
    - shell: docker exec pvpc rake db:migrate
    - shell: docker exec pvpc rake db:seed
    - shell: docker stop pvpc
    - shell: docker stop redis
    - shell: docker stop rabbitmq
    - shell: docker stop postgres
