---
- hosts: vm
  tasks:
    - shell: docker {{ item[1] }} {{ item[0] }}
      ignore_errors: yes
      with_nested:
        - ['pvpc', 'redis', 'rabbitmq', 'postgres']
        - ['stop', 'rm', 'rmi']
    - file: path=/home/vagrant/pvpc state=absent
