---
- hosts: vm
  tasks:
    - apt: name=git
      sudo: yes
    - shell: curl -sSL https://get.docker.com/ | sh
    - shell: usermod -aG docker vagrant
      sudo: yes
    - shell: shutdown -r now
      sudo: yes
    - local_action: wait_for host={{ inventory_hostname }} port=22
